### ISSUE TITLE
PHP migrations are failing

### ISSUE THREAD

**Issue by dorantor** [PHPixie/Migrate#5]
Trying to run phpixie/project-auth with pgsql. Somehow I managed to fix missing "framework:*" console and some other things. But php-migrations seems to be in completely non-working condition. Or something is missing in docs.
```
<?php
// 1_init_db.sql
$this->execute('CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);');

$this->message('Created users table.');

$this->execute('CREATE TABLE user_tokens (
  series VARCHAR(50) PRIMARY KEY NOT NULL,
  user_id INT DEFAULT NULL,
  challenge VARCHAR(50) DEFAULT NULL,
  expires BIGINT DEFAULT NULL
);');

$this->message('Created user_tokens table.');

$this->execute('CREATE TABLE admins (
  id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);');

$this->message('Created admins table.');
```
And result I got:
```
$ php ./console framework:migrate
Running 1_init_db
----
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
----
PHP Fatal error:  Uncaught ErrorException: Invalid argument supplied for foreach() in <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php:92
Stack trace:
#0 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Handlers.php(33): PHPixie\Debug\Handlers->handleError(2, 'Invalid argumen...', '/home/vagrant/p...', 92)
#1 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(92): PHPixie\Debug\Handlers->PHPixie\Debug\{closure}(2, 'Invalid argumen...', '/home/vagrant/p...', 92, Array)
#2 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(123): PHPixie\Debug\Tracer\Trace\Element->shortArgumentDumps()
#3 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(178): PHPixie\Debug\Tracer\Trace\Element->context(true)
#4 <myProjectPath>/vendor/phpixie/debug/src/ in <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php on line 92

Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php:92
Stack trace:
#0 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Handlers.php(33): PHPixie\Debug\Handlers->handleError(2, 'Invalid argumen...', '/home/vagrant/p...', 92)
#1 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(92): PHPixie\Debug\Handlers->PHPixie\Debug\{closure}(2, 'Invalid argumen...', '/home/vagrant/p...', 92, Array)
#2 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(123): PHPixie\Debug\Tracer\Trace\Element->shortArgumentDumps()
#3 <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php(178): PHPixie\Debug\Tracer\Trace\Element->context(true)
#4 <myProjectPath>/vendor/phpixie/debug/src/ in <myProjectPath>/vendor/phpixie/debug/src/PHPixie/Debug/Tracer/Trace/Element.php on line 92
```

And migrations in sql form ran smoothly:
```
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

-- statement

CREATE TABLE user_tokens (
  series VARCHAR(50) PRIMARY KEY NOT NULL,
  user_id INT DEFAULT NULL,
  challenge VARCHAR(50) DEFAULT NULL,
  expires BIGINT DEFAULT NULL
);

-- statement

CREATE TABLE admins (
  id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
```

**Comment by dracony** [comment]
Your problem is with the ';' in the ->execute() call. PDO queries should be without ';'

**Comment by dorantor** [comment]
My bad, sorry.
